### ISSUE TITLE
Can't install/build on raspberrypi (node@v0.11.4)

### ISSUE THREAD

**Issue by fabiosantoscode** [shama/gaze#93]
Don't know if it's supposed to be installed in a raspi, or in this version of node (you state that it's compatible with 0.10, but not 0.11), but this is the error I get:

```
pi@raspberrypi ~ $ npm install gaze
[Lots of output...]

> gaze@0.6.2 install /home/pi/node_modules/gaze
> node-gyp rebuild

make: Entering directory `/home/pi/node_modules/gaze/build'
  CXX(target) Release/obj.target/pathwatcher/src/main.o
  CXX(target) Release/obj.target/pathwatcher/src/common.o
  CXX(target) Release/obj.target/pathwatcher/src/handle_map.o
../src/handle_map.cc: In member function ‘bool HandleMap::Erase(WatcherHandle)’:
../src/handle_map.cc:41:36: error: no matching function for call to ‘NanDisposePersistent(NanUnsafePersistent<v8::Value>&)’
../src/handle_map.cc:41:36: note: candidate is:
../node_modules/nan/nan.h:384:28: note: template<class T> void NanDisposePersistent(v8::Persistent<T>&)
../src/handle_map.cc: In member function ‘void HandleMap::Clear()’:
../src/handle_map.cc:48:38: error: no matching function for call to ‘NanDisposePersistent(NanUnsafePersistent<v8::Value>&)’
../src/handle_map.cc:48:38: note: candidate is:
../node_modules/nan/nan.h:384:28: note: template<class T> void NanDisposePersistent(v8::Persistent<T>&)
make: *** [Release/obj.target/pathwatcher/src/handle_map.o] Error 1
make: Leaving directory `/home/pi/node_modules/gaze/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:103:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.10.25+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_modules/gaze
gyp ERR! node -v v0.11.4
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0
```

npm version is 1.3.4

I'm trying to install gulp, but gaze is a dependency.

Should I even be trying to install this on a raspberry pi?

Thanks --
